jobs:
  job0:
    runs-on:
    - self-hosted
    - Linux
    - X64
    - nix
    - spec2006
    steps:
    - uses: actions/checkout@v4
    - run: 'nix-build /nix/store/hmiran07qslfkfwm56wwgivm6qj10w7s-nyancat --argstr
        cores 1 --argstr linuxVersion default '
    timeout-minutes: 10080
  job1:
    runs-on:
    - self-hosted
    - Linux
    - X64
    - nix
    - spec2006
    steps:
    - uses: actions/checkout@v4
    - run: 'nix-build /nix/store/hmiran07qslfkfwm56wwgivm6qj10w7s-nyancat --argstr
        cores 1 --argstr linuxVersion latest '
    timeout-minutes: 10080
  job10:
    runs-on:
    - self-hosted
    - Linux
    - X64
    - nix
    - spec2006
    steps:
    - uses: actions/checkout@v4
    - run: 'nix-build /nix/store/cv1lr01a945xqgjdln0ph9ij18l86x4p-openblas --argstr
        TARGET RISCV64_ZVL128B --argstr cores 2 --argstr linuxVersion default '
    timeout-minutes: 10080
  job11:
    runs-on:
    - self-hosted
    - Linux
    - X64
    - nix
    - spec2006
    steps:
    - uses: actions/checkout@v4
    - run: 'nix-build /nix/store/cv1lr01a945xqgjdln0ph9ij18l86x4p-openblas --argstr
        TARGET RISCV64_ZVL128B --argstr cores 2 --argstr linuxVersion latest '
    timeout-minutes: 10080
  job12:
    runs-on:
    - self-hosted
    - Linux
    - X64
    - nix
    - spec2006
    steps:
    - uses: actions/checkout@v4
    - run: 'nix-build /nix/store/4ixn0d94lsa94j9cvgh8mlsjg0ngaid8-spec2006 --argstr
        cores 1 --arg enableVector true --argstr linuxVersion default --arg src /spec2006.tar.gz '
    timeout-minutes: 10080
  job13:
    runs-on:
    - self-hosted
    - Linux
    - X64
    - nix
    - spec2006
    steps:
    - uses: actions/checkout@v4
    - run: 'nix-build /nix/store/4ixn0d94lsa94j9cvgh8mlsjg0ngaid8-spec2006 --argstr
        cores 1 --arg enableVector true --argstr linuxVersion latest --arg src /spec2006.tar.gz '
    timeout-minutes: 10080
  job14:
    runs-on:
    - self-hosted
    - Linux
    - X64
    - nix
    - spec2006
    steps:
    - uses: actions/checkout@v4
    - run: 'nix-build /nix/store/4ixn0d94lsa94j9cvgh8mlsjg0ngaid8-spec2006 --argstr
        cores 1 --arg enableVector false --argstr linuxVersion default --arg src /spec2006.tar.gz '
    timeout-minutes: 10080
  job15:
    runs-on:
    - self-hosted
    - Linux
    - X64
    - nix
    - spec2006
    steps:
    - uses: actions/checkout@v4
    - run: 'nix-build /nix/store/4ixn0d94lsa94j9cvgh8mlsjg0ngaid8-spec2006 --argstr
        cores 1 --arg enableVector false --argstr linuxVersion latest --arg src /spec2006.tar.gz '
    timeout-minutes: 10080
  job16:
    runs-on:
    - self-hosted
    - Linux
    - X64
    - nix
    - spec2006
    steps:
    - uses: actions/checkout@v4
    - run: 'nix-build /nix/store/4ixn0d94lsa94j9cvgh8mlsjg0ngaid8-spec2006 --argstr
        cores 2 --arg enableVector true --argstr linuxVersion default --arg src /spec2006.tar.gz '
    timeout-minutes: 10080
  job17:
    runs-on:
    - self-hosted
    - Linux
    - X64
    - nix
    - spec2006
    steps:
    - uses: actions/checkout@v4
    - run: 'nix-build /nix/store/4ixn0d94lsa94j9cvgh8mlsjg0ngaid8-spec2006 --argstr
        cores 2 --arg enableVector true --argstr linuxVersion latest --arg src /spec2006.tar.gz '
    timeout-minutes: 10080
  job18:
    runs-on:
    - self-hosted
    - Linux
    - X64
    - nix
    - spec2006
    steps:
    - uses: actions/checkout@v4
    - run: 'nix-build /nix/store/4ixn0d94lsa94j9cvgh8mlsjg0ngaid8-spec2006 --argstr
        cores 2 --arg enableVector false --argstr linuxVersion default --arg src /spec2006.tar.gz '
    timeout-minutes: 10080
  job19:
    runs-on:
    - self-hosted
    - Linux
    - X64
    - nix
    - spec2006
    steps:
    - uses: actions/checkout@v4
    - run: 'nix-build /nix/store/4ixn0d94lsa94j9cvgh8mlsjg0ngaid8-spec2006 --argstr
        cores 2 --arg enableVector false --argstr linuxVersion latest --arg src /spec2006.tar.gz '
    timeout-minutes: 10080
  job2:
    runs-on:
    - self-hosted
    - Linux
    - X64
    - nix
    - spec2006
    steps:
    - uses: actions/checkout@v4
    - run: 'nix-build /nix/store/hmiran07qslfkfwm56wwgivm6qj10w7s-nyancat --argstr
        cores 2 --argstr linuxVersion default '
    timeout-minutes: 10080
  job3:
    runs-on:
    - self-hosted
    - Linux
    - X64
    - nix
    - spec2006
    steps:
    - uses: actions/checkout@v4
    - run: 'nix-build /nix/store/hmiran07qslfkfwm56wwgivm6qj10w7s-nyancat --argstr
        cores 2 --argstr linuxVersion latest '
    timeout-minutes: 10080
  job4:
    runs-on:
    - self-hosted
    - Linux
    - X64
    - nix
    - spec2006
    steps:
    - uses: actions/checkout@v4
    - run: 'nix-build /nix/store/cv1lr01a945xqgjdln0ph9ij18l86x4p-openblas --argstr
        TARGET RISCV64_GENERIC --argstr cores 1 --argstr linuxVersion default '
    timeout-minutes: 10080
  job5:
    runs-on:
    - self-hosted
    - Linux
    - X64
    - nix
    - spec2006
    steps:
    - uses: actions/checkout@v4
    - run: 'nix-build /nix/store/cv1lr01a945xqgjdln0ph9ij18l86x4p-openblas --argstr
        TARGET RISCV64_GENERIC --argstr cores 1 --argstr linuxVersion latest '
    timeout-minutes: 10080
  job6:
    runs-on:
    - self-hosted
    - Linux
    - X64
    - nix
    - spec2006
    steps:
    - uses: actions/checkout@v4
    - run: 'nix-build /nix/store/cv1lr01a945xqgjdln0ph9ij18l86x4p-openblas --argstr
        TARGET RISCV64_GENERIC --argstr cores 2 --argstr linuxVersion default '
    timeout-minutes: 10080
  job7:
    runs-on:
    - self-hosted
    - Linux
    - X64
    - nix
    - spec2006
    steps:
    - uses: actions/checkout@v4
    - run: 'nix-build /nix/store/cv1lr01a945xqgjdln0ph9ij18l86x4p-openblas --argstr
        TARGET RISCV64_GENERIC --argstr cores 2 --argstr linuxVersion latest '
    timeout-minutes: 10080
  job8:
    runs-on:
    - self-hosted
    - Linux
    - X64
    - nix
    - spec2006
    steps:
    - uses: actions/checkout@v4
    - run: 'nix-build /nix/store/cv1lr01a945xqgjdln0ph9ij18l86x4p-openblas --argstr
        TARGET RISCV64_ZVL128B --argstr cores 1 --argstr linuxVersion default '
    timeout-minutes: 10080
  job9:
    runs-on:
    - self-hosted
    - Linux
    - X64
    - nix
    - spec2006
    steps:
    - uses: actions/checkout@v4
    - run: 'nix-build /nix/store/cv1lr01a945xqgjdln0ph9ij18l86x4p-openblas --argstr
        TARGET RISCV64_ZVL128B --argstr cores 1 --argstr linuxVersion latest '
    timeout-minutes: 10080
  quick-test:
    runs-on:
    - self-hosted
    - Linux
    - X64
    - nix
    - spec2006
    steps:
    - uses: actions/checkout@v4
    - run: "for example in examples/*/default.nix; do\n  nix-instantiate $example\
        \ --arg src $(ls -d /spec2006* | head -n1) -A cpt\ndone\n"
name: build-deterload
'on':
  push:
    branches:
    - actions
    paths:
    - '**'
    - '!docs/**'
