name: build-deterload
on:
  push:
    branches:
      # push to data branch will not trigger this workflow
      - main
    paths:
      # changes in docs/ will not trigger this workflow
      - "**"
      - "!docs/**"
jobs:
  build-deterload:
    timeout-minutes: 10080 # one week (spec2006 with enableVector needs about 4 days)
    runs-on: [self-hosted, Linux, X64, nix, spec2006]
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - run: nix-build -A openblas.cpt -o result-openblas
    - run: nix-build -A spec2006.cpt --arg spec2006-src $(ls -d /spec2006* | head -n1) -j29 -o result-spec2006
    - run: |
        git rev-parse HEAD > /tmp/rev
        (TZ=UTC-8 date +%y%m%d%H%M%S && cat /tmp/rev && echo && readlink result-openblas) | tr '\n' ',' > /tmp/openblas.txt
        echo >> /tmp/openblas.txt # add a newline
        (TZ=UTC-8 date +%y%m%d%H%M%S && cat /tmp/rev && echo && for i in result-spec2006 result-spec2006/*; do readlink $i; done) | tr '\n' ',' > /tmp/spec2006.txt
        echo >> /tmp/spec2006.txt # add a newline
    - uses: actions/checkout@v4
      with:
        ref: data
    - run: |
        cat openblas.txt >> /tmp/openblas.txt; mv /tmp/openblas.txt openblas.txt; git add openblas.txt
        cat spec2006.txt >> /tmp/spec2006.txt; mv /tmp/spec2006.txt spec2006.txt; git add spec2006.txt
        git config --global user.name xieby1Runner
        git config --global user.email "miao@wang.zhi"
        git commit -m "update data for git commit $(cat /tmp/rev)"
        git push

  quick-test:
    runs-on: [self-hosted, Linux, X64, nix, spec2006]
    steps:
    - uses: actions/checkout@v4
    - run: |
        for example in examples/*.nix; do
          for folder in benchmarks/*/; do
            benchmark=${folder%/}
            nix-instantiate $example --arg spec2006-src $(ls -d /spec2006* | head -n1) -A ${benchmark##*/}.cpt
          done
        done
