name: build-deterload
on: [push]
jobs:
  build-deterload:
    timeout-minutes: 2880
    runs-on: [self-hosted, Linux, X64, nix]
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - run: nix-build -A openblas
    - run: nix-build -A spec2006 --arg src /nfs/share/home/spec2006.tar.gz -j29
